services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sideproject
    ports:
      - "3308:3306"
    restart: unless-stopped
    volumes:
      - backend_volume:/var/lib/mysql
    networks:
      - backend_network

#  app:
#    container_name: app
#    build:
#      context: .
#      dockerfile: docker/app/Dockerfile
#    ports:
#      - "8888:8080"
#    env_file:
#      - env
#    restart: always
#    volumes:
#      - .:/app
#      - ./build/classes/java/main:/app/build/classes/java/main
#
#    networks:
#      - backend_network
#    depends_on:
#      - mysql
  rabbit_mq:
    image: rabbitmq:3-management
    container_name: rabbit_mq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: pass
    restart: unless-stopped
    networks:
      - backend_network

volumes:
    backend_volume:

networks:
    backend_network:


